name: Add two numbers
on:
  workflow_dispatch:
    inputs:
      num1:
        description: "First number"
        required: true
        default: "0"
      num2:
        description: "Second number"
        required: true
        default: "0"
